name: sample-workflow
on:
  push:
    branches: [develop]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: cheks-out your repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v2
    - name: use echo command
      runs: echo "sample-workflow"
